version : "3.9"

services :
  db :
    image : postgres:14.1-alpine
    environment :
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging :
      options :
        max-size : 10m
        max-file : "3"
    ports :
      - '5432:5432'
    volumes :
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
  #        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis_master :
    image : 'bitnami/redis:latest'
    container_name : app_redis
    ports :
      - "6382:6379"
    environment :
      - REDIS_USER=master
      - REDIS_PASSWORD=ish@kap7712CacheConfig
  zookeeper :
    image : confluentinc/cp-zookeeper:latest
    environment :
      ZOOKEEPER_CLIENT_PORT : 2181
      ZOOKEEPER_TICK_TIME : 2000
    ports :
      - "22181:2181"
  kafka :
    image : confluentinc/cp-kafka:latest
    depends_on :
      - zookeeper
    ports :
      - "29092:29092"
    environment :
      KAFKA_BROKER_ID : 1
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
